version: 2
jobs:
  test:
    docker:
      - image: circleci/buildpack-deps:14.04-browsers
    steps:
      - checkout
      - run: java -version
      - run: sudo apt-get install maven
      - run: mvn test
      - store_artifacts:
                path: target/surefire-reports
                destination: tr1
                path: build/reports/tests
                destination: tr2
workflows:
  version: 2
  build_and_test:
    jobs:
      - test